create table users (
    id bigint generated by default as identity primary key,
    name varchar(160) not null,
    cpf varchar(14),
    cnpj varchar(18),
    role varchar(30) not null,
    verified boolean not null default false,
    created_at timestamp not null,
    constraint uk_users_cpf unique (cpf),
    constraint uk_users_cnpj unique (cnpj)
);

create table institutions (
    id bigint generated by default as identity primary key,
    legal_name varchar(180) not null,
    cnpj varchar(18) not null,
    pharmacist_name varchar(160) not null,
    pharmacist_registry varchar(40) not null,
    status varchar(30) not null,
    latitude numeric(9, 6) not null,
    longitude numeric(9, 6) not null,
    created_at timestamp not null,
    constraint uk_institutions_cnpj unique (cnpj)
);

create table medication_blacklist (
    id bigint generated by default as identity primary key,
    blocked_type_code integer,
    active_ingredient varchar(160),
    commercial_name varchar(160),
    reason varchar(260) not null,
    active boolean not null default true,
    created_at timestamp not null
);

create table medications (
    id bigint generated by default as identity primary key,
    donor_id bigint not null,
    donor_cpf varchar(14) not null,
    commercial_name varchar(160) not null,
    active_ingredient varchar(160) not null,
    concentration varchar(80) not null,
    manufacturer varchar(160) not null,
    lot_number varchar(60) not null,
    expiration_date date not null,
    quantity_available integer not null,
    medication_type_code integer not null,
    front_photo_url varchar(500) not null,
    blister_photo_url varchar(500) not null,
    storage_declaration boolean not null,
    status varchar(30) not null,
    created_at timestamp not null,
    updated_at timestamp not null,
    constraint ck_medications_quantity_positive check (quantity_available > 0),
    constraint ck_medications_storage_declaration check (storage_declaration = true)
);

create index idx_medications_search on medications (commercial_name, active_ingredient, lot_number, expiration_date);
create index idx_medications_status on medications (status);

create table donation_matches (
    id bigint generated by default as identity primary key,
    medication_id bigint not null,
    donor_id bigint not null,
    institution_id bigint not null,
    radius_km numeric(6, 2) not null,
    donor_latitude numeric(9, 6) not null,
    donor_longitude numeric(9, 6) not null,
    distance_km numeric(8, 3) not null,
    matched_at timestamp not null,
    accepted_at timestamp,
    completed_at timestamp,
    validation_code varchar(120),
    status varchar(30) not null,
    delivery_deadline date,
    constraint fk_donation_matches_medication foreign key (medication_id) references medications (id),
    constraint fk_donation_matches_institution foreign key (institution_id) references institutions (id)
);

create index idx_donation_matches_institution_status on donation_matches (institution_id, status);

create table audit_events (
    id bigint generated by default as identity primary key,
    aggregate_type varchar(80) not null,
    aggregate_id bigint not null,
    action varchar(80) not null,
    actor_document varchar(18) not null,
    details varchar(1000) not null,
    occurred_at timestamp not null
);

create index idx_audit_events_aggregate on audit_events (aggregate_type, aggregate_id);
